version: 2
workflows:
  version: 2
  build_format:
    jobs:
      - format
      - build
jobs:
  format:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Check Format
          command: "! go fmt ./... 2>&1 | read"
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -mod=readonly ./...